import json, re, urllib.request, urllib.error, xml.etree.ElementTree as ET
from html.parser import HTMLParser
BASE='http://127.0.0.1:8080'
class Page(HTMLParser):
    def __init__(self,text):
        super().__init__(); self.canonical=''; self.robots=''; self.mains=0; self.h1=0; self.schemas=[]; self.script=False; self.buf='';self.feed(text)
    def handle_starttag(self,tag,attrs):
        a=dict(attrs)
        if tag=='link' and a.get('rel')=='canonical':self.canonical=a.get('href','')
        if tag=='meta' and a.get('name')=='robots':self.robots=a.get('content','')
        if tag=='main':self.mains+=1
        if tag=='h1':self.h1+=1
        if tag=='script' and a.get('type')=='application/ld+json':self.script=True;self.buf=''
    def handle_data(self,data):
        if self.script:self.buf+=data
    def handle_endtag(self,tag):
        if tag=='script' and self.script:self.schemas.append(json.loads(self.buf));self.script=False

def get(path):
    try:r=urllib.request.urlopen(BASE+path,timeout=15)
    except urllib.error.HTTPError as e:r=e
    text=r.read().decode();return r.status,r.geturl(),r.headers,text,Page(text)
def check(ok,msg):
    if not ok:raise AssertionError(msg)
series='/products.php?category=test-cameras&brand=Hikvision&series=test-series'
s,u,h,t,p=get(series+'&page=2');check(s==200 and p.canonical==BASE+series+'&page=2','Self-referencing page 2');check(t.count('class="prod-card h-100"')==2,'Page 2 has remaining two products');check('Page 2' in t and p.mains==1,'Page title and single main');check(p.robots=='index, follow','Series indexable')
for path in [series+'&page=99',series+'&page=abc',series+'&page=0','/products.php?category=test-cameras&series=missing','/products.php?category=missing','/products.php?category=test-cameras&brand=Unknown',series.replace('Hikvision','Dahua'),'/product/inactive-camera','/missing-page']:
    check(get(path)[0]==404,'404: '+path)
s,u,h,t,p=get('/products.php?category=test-series');check(u==BASE+series and p.canonical==BASE+series,'Legacy child redirect')
s,u,h,t,p=get('/products.php?category=test-cameras&brand=Hikvision');check('Other Hikvision products' in t and 'test-series' in t,'Series and direct access links')
s,u,h,t,p=get('/products.php?category=test-cameras&brand=Dahua&direct=1');check('Legacy Camera' in t,'Parent products reachable')
s,u,h,t,p=get('/products.php?category=test-cameras&brand=Dahua&series=mixed-series');check('Mixed camera' in t and 'noindex' in p.robots,'Mixed-brand filter')
s,u,h,t,p=get('/products.php?category=empty-category');check('noindex' in p.robots,'Empty noindex')
s,u,h,t,p=get('/search.php?q=Test&page=2');check('/products.php?q=Test&page=2' in u and t.count('class="prod-card h-100"')==2 and 'noindex' in p.robots,'Search paginated')
s,u,h,t,p=get('/product/test-camera-1');product=next(x for x in p.schemas if x['@type']=='Product');check('offers' not in product and 'Price on request' in t and '100% OFF' not in t,'Visible and structured price agree')
check(get('/product.php?slug=test-camera-2')[1]==BASE+'/product/test-camera-2','Product alias redirect')
check(get('/index.php')[1]==BASE+'/','Homepage alias redirect')
for path in ['/products.php?q%5B%5D=bad','/product.php?slug%5B%5D=bad','/search.php?q%5B%5D=bad']:
    check(get(path)[0]<500,'Array input handled')
s,u,h,t,p=get('/estimate.php?ref=unknown');check(s==404 and 'noindex' in h.get('X-Robots-Tag','') and 'no-store' in h.get('Cache-Control',''),'Private estimates')
home='/home-cctv-installation-karachi'
s,u,h,t,p=get(home)
check(s==200 and p.canonical==BASE+home and p.robots=='index, follow' and p.h1==1,'Home CCTV canonical, indexing and single H1')
check('home-cctv.css' in t and t.find('home-cctv.css')<t.find('</head>'),'Home CCTV stylesheet loads in head')
check('id="plan"' in t and 'id="coverage"' in t and 'id="equipment"' in t and 'id="questions"' in t,'Home CCTV planning sections render')
check(t.count('class="homecam-faq"')>=15 and 'Will the cameras record if the internet is down?' in t,'Crawlable, visible homeowner questions')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Home CCTV service schema')
check('FAQPage' not in [x.get('@type') for x in p.schemas],'No deprecated FAQ rich-result markup')
check('wa.me/923091243189' in t and '/calculator.php' in t,'Home CCTV contact and calculator actions')
check(get(home+'.php')[1]==BASE+home and get(home+'/')[1]==BASE+home,'Home CCTV URL aliases redirect')
s,u,h,t,p=get('/')
check('href="'+BASE+home+'"' in t and 'Explore the Guide' in t,'Homepage service card links to guide')
office='/office-cctv-installation-karachi'
s,u,h,t,p=get(office)
check(s==200 and p.canonical==BASE+office and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Office CCTV canonical, indexability and one main/H1')
check('Office CCTV Installation' in t and 'id="office-plan"' in t and 'id="office-coverage"' in t and 'id="office-system"' in t and 'id="office-handover"' in t,'Office service content is rendered')
check(t.count('class="homecam-faq"')>=10 and 'Can managers view different cameras' in t and 'Will office CCTV continue recording' in t,'Useful visible office questions')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Office service schema')
check('FAQPage' not in [x.get('@type') for x in p.schemas],'Avoid ineligible office FAQ markup')
check('home-cctv.css' in t and t.find('home-cctv.css')<t.find('</head>') and 'service-office' in t,'Office CSS and existing illustration')
check('wa.me/923091243189' in t and '/calculator.php' in t,'Office survey and calculator actions')
check(get(office+'.php')[1]==BASE+office and get(office+'/')[1]==BASE+office,'Office aliases redirect')
s,u,h,t,p=get('/')
check('href="'+BASE+office+'"' in t and 'Office &amp; Commercial CCTV' in t,'Homepage office service card links to guide')
shop='/shop-cctv-installation-karachi'
s,u,h,t,p=get(shop)
check(s==200 and p.canonical==BASE+shop and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Shop CCTV canonical, indexability and one main/H1')
check('Shop CCTV Installation' in t and 'id="retail-plan"' in t and 'id="retail-coverage"' in t and 'id="retail-system"' in t and 'id="retail-incident"' in t,'Retail service content is rendered')
check(t.count('class="homecam-faq"')>=12 and 'Should a camera point directly at the card terminal?' in t and 'Does a CCTV system replace stock control or POS records?' in t,'Useful visible retail questions')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Shop CCTV service schema')
check('FAQPage' not in [x.get('@type') for x in p.schemas],'Avoid ineligible shop FAQ markup')
check('home-cctv.css' in t and t.find('home-cctv.css')<t.find('</head>') and 'service-shop' in t,'Shop CSS and existing illustration')
check('wa.me/923091243189' in t and '/calculator.php' in t and '/products.php' in t,'Shop contact, calculator and product actions')
check(get(shop+'.php')[1]==BASE+shop and get(shop+'/')[1]==BASE+shop,'Shop aliases redirect')
s,u,h,t,p=get('/')
check('href="'+BASE+shop+'"' in t and 'Shop &amp; Retail CCTV' in t,'Homepage shop service card links to guide')
maintenance='/cctv-maintenance-karachi'
s,u,h,t,p=get(maintenance)
check(s==200 and p.canonical==BASE+maintenance and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Maintenance canonical, indexability and one main/H1')
check('CCTV Maintenance' in t and 'id="maintenance-audit"' in t and 'id="maintenance-checks"' in t and 'id="maintenance-faults"' in t and 'id="maintenance-handover"' in t,'Maintenance service content is rendered')
check(t.count('class="homecam-faq"')>=12 and 'What does DVR or NVR beeping mean?' in t and 'Should firmware be updated during every maintenance visit?' in t,'Useful visible maintenance questions')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Maintenance Service schema')
check('FAQPage' not in [x.get('@type') for x in p.schemas],'Avoid ineligible maintenance FAQ markup')
check('home-cctv.css' in t and t.find('home-cctv.css')<t.find('</head>') and 'service-amc' in t,'Maintenance CSS and existing illustration')
check('wa.me/923091243189' in t and '/office-cctv-installation-karachi' in t and '/shop-cctv-installation-karachi' in t and '/home-cctv-installation-karachi' in t,'Maintenance contact and internal links')
check(get(maintenance+'.php')[1]==BASE+maintenance and get(maintenance+'/')[1]==BASE+maintenance,'Maintenance aliases redirect')
check('href="'+BASE+maintenance+'"' in get(shop)[3],'Existing shop guide links to maintenance')
ip='/ip-camera-installation-karachi'
s,u,h,t,p=get(ip)
check(s==200 and p.canonical==BASE+ip and p.robots=='index, follow' and p.h1==1 and p.mains==1,'IP camera canonical, indexability and one main/H1')
check('IP &amp; WIRELESS' in t and 'id="ip-choice"' in t and 'id="ip-design"' in t and 'id="ip-recording"' in t and 'id="ip-handover"' in t,'IP camera service content is rendered')
check(t.count('class="homecam-faq"')>=12 and 'Are wireless CCTV cameras completely cable-free?' in t and 'Will a Wi-Fi extender fix a weak camera signal?' in t,'Useful visible IP and wireless questions')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'IP camera Service schema')
check('FAQPage' not in [x.get('@type') for x in p.schemas],'Avoid ineligible IP camera FAQ markup')
check('home-cctv.css' in t and t.find('home-cctv.css')<t.find('</head>') and 'service-ip' in t,'IP camera CSS and existing illustration')
check('wa.me/923091243189' in t and '/calculator.php' in t and '/products.php' in t and '/cctv-maintenance-karachi' in t,'IP camera contact and useful internal actions')
check(get(ip+'.php')[1]==BASE+ip and get(ip+'/')[1]==BASE+ip,'IP camera aliases redirect')
check('href="'+BASE+ip+'"' in get(maintenance)[3],'Existing maintenance guide links to IP camera planning')
access='/access-control-installation-karachi'
s,u,h,t,p=get(access)
check(s==200 and p.canonical==BASE+access and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Access control canonical, indexability and one main/H1')
check('ACCESS CONTROL' in t and 'id="access-plan"' in t and 'id="access-door"' in t and 'id="access-system"' in t and 'id="access-handover"' in t,'Access control service content is rendered')
check(t.count('class="homecam-faq"')>=12 and 'Is access control the same as an attendance machine?' in t and 'What happens to the door during a power failure?' in t,'Useful visible access control questions')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Access control Service schema')
check('FAQPage' not in [x.get('@type') for x in p.schemas],'Avoid ineligible access control FAQ markup')
check('home-cctv.css' in t and t.find('home-cctv.css')<t.find('</head>') and 'service-access' in t,'Access control CSS and existing illustration')
check('wa.me/923091243189' in t and '/office-cctv-installation-karachi' in t and '/ip-camera-installation-karachi' in t and '/cctv-maintenance-karachi' in t,'Access control contact and useful internal links')
check(get(access+'.php')[1]==BASE+access and get(access+'/')[1]==BASE+access,'Access control aliases redirect')
check('href="'+BASE+access+'"' in get(ip)[3],'Existing IP camera guide links to access control')
intercom='/video-door-intercom-installation-karachi'
s,u,h,t,p=get(intercom)
check(s==200 and p.canonical==BASE+intercom and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Video intercom canonical, indexability and one main/H1')
check('VIDEO DOOR INTERCOM' in t and 'id="intercom-plan"' in t and 'id="intercom-wiring"' in t and 'id="intercom-system"' in t and 'id="intercom-handover"' in t,'Video intercom service content is rendered')
check(t.count('class="homecam-faq"')>=12 and 'Should I choose an analogue or IP video intercom?' in t and 'Can I answer the intercom on my mobile phone?' in t,'Useful visible video intercom questions')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Video intercom Service schema')
check('FAQPage' not in [x.get('@type') for x in p.schemas],'Avoid ineligible video intercom FAQ markup')
check('home-cctv.css' in t and t.find('home-cctv.css')<t.find('</head>') and 'service-access' in t,'Video intercom CSS and existing illustration')
check('wa.me/923091243189' in t and '/access-control-installation-karachi' in t and '/ip-camera-installation-karachi' in t and '/home-cctv-installation-karachi' in t,'Video intercom contact and useful internal links')
check(get(intercom+'.php')[1]==BASE+intercom and get(intercom+'/')[1]==BASE+intercom,'Video intercom aliases redirect')
check('href="'+BASE+intercom+'"' in get(access)[3],'Existing access control guide links to video intercom')
check(get('/office-cctv-installation-karachi')[4].h1==1,'Office CCTV page still works')
check(get('/home-cctv-installation-karachi')[4].h1==1,'Home CCTV page still works')
imou='/imou-wireless-cameras-karachi'
s,u,h,t,p=get(imou)
check(s==200 and p.canonical==BASE+imou and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Imou canonical and crawlable page')
check(t.count('class="imou-product"')==6 and t.count('static-website.imou.com/')>=6,'Six illustrated Imou models')
check(all(name in t for name in ['Ranger RC-R1','Ranger 2 Dual','Ranger 2 Pro 4K','Cruiser 2','Cruiser Dual 2','N110W / N118W']),'Named camera and recorder range')
check(all('id="'+section+'"' in t for section in ['imou-models','imou-selection','imou-recording','imou-installation','imou-questions']),'Practical guide sections')
check('4K HDMI' in t and 'power' in t and t.count('class="homecam-faq"')>=8,'Compatibility and power guidance')
items=next(x for x in p.schemas if x.get('@type')=='ItemList')['itemListElement']
check(len(items)==6 and all(x['item']['image'].startswith('https://static-website.imou.com/') and 'offers' not in x['item'] for x in items),'Product images without invented offers')
check(get(imou+'.php')[1]==BASE+imou and get(imou+'/')[1]==BASE+imou,'Imou aliases redirect')
check('href="'+BASE+imou+'"' in get(ip)[3],'Imou guide discoverable internally')
storage='/cctv-storage-upgrade-karachi'
s,u,h,t,p=get(storage)
check(s==200 and p.canonical==BASE+storage and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Storage canonical and crawlable layout')
check(all('id="'+x+'"' in t for x in ['storage-assessment','storage-calculation','storage-upgrade','storage-handover','storage-questions']),'Storage planning sections')
check('172.8GB' in t and '2,419.2GB' in t and 'initialisation' in t and 'old disk' in t,'Retention calculation and preservation guidance')
check(t.count('class="homecam-faq"')==10 and 'recovery of overwritten' in t,'Useful storage questions and limits')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Storage Service schema')
check(get(storage+'.php')[1]==BASE+storage and get(storage+'/')[1]==BASE+storage,'Storage aliases redirect')
check('href="'+BASE+storage+'"' in get(maintenance)[3],'Storage inbound link')
power='/cctv-power-backup-ups-karachi'
s,u,h,t,p=get(power)
check(s==200 and p.canonical==BASE+power and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Power backup canonical and crawlable layout')
check(all('id="'+x+'"' in t for x in ['power-path','power-sizing','power-design','power-handover','power-questions']),'Power planning sections')
check('120W' in t and '240Wh' in t and 'UPS VA and watt ratings' in t,'Transparent load and runtime example')
check(t.count('class="homecam-faq"')==10 and 'qualified electrician' in t and 'lifetime guarantee' in t,'Useful safety and limitation guidance')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Power backup Service schema')
check(get(power+'.php')[1]==BASE+power and get(power+'/')[1]==BASE+power,'Power backup aliases redirect')
check('href="'+BASE+power+'"' in get(storage)[3],'Power guide has a contextual inbound link')
mobile='/cctv-mobile-viewing-setup-karachi'
s,u,h,t,p=get(mobile)
check(s==200 and p.canonical==BASE+mobile and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Mobile viewing canonical and crawlable layout')
check(all('id="'+x+'"' in t for x in ['mobile-assessment','mobile-security','mobile-network','mobile-handover','mobile-questions']),'Mobile viewing planning sections')
check('customer-controlled recovery' in t and 'mobile data or another network' in t and 'do not bypass account ownership' in t,'Secure ownership and remote test guidance')
check(t.count('class="homecam-faq"')==10 and 'port forwarding' in t and 'Local recording and remote access are separate' in t,'Useful mobile viewing questions')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Mobile viewing Service schema')
check(get(mobile+'.php')[1]==BASE+mobile and get(mobile+'/')[1]==BASE+mobile,'Mobile viewing aliases redirect')
check('href="'+BASE+mobile+'"' in get(ip)[3],'Mobile viewing guide has contextual inbound link')
cabling='/cctv-cabling-installation-karachi'
s,u,h,t,p=get(cabling)
check(s==200 and p.canonical==BASE+cabling and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Cabling canonical and crawlable layout')
check(all('id="'+x+'"' in t for x in ['cable-assessment','cable-design','cable-installation','cable-testing','cable-questions']),'Cabling planning sections')
check('PoE standard and total power budget' in t and 'Avoid unapproved joins' in t and 'camera-to-port schedule' in t,'Cable, power and documentation guidance')
check(t.count('class="accordion-item"')==10 and 'qualified electrician' not in t and 'one price for every building' in t,'Useful cabling questions without unsupported claims')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Cabling Service schema')
check(get(cabling+'.php')[1]==BASE+cabling and get(cabling+'/')[1]==BASE+cabling,'Cabling aliases redirect')
check('href="'+BASE+cabling+'"' in get(maintenance)[3],'Cabling guide has contextual inbound link')
audio='/cctv-camera-audio-installation-karachi'
s,u,h,t,p=get(audio)
check(s==200 and p.canonical==BASE+audio and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Audio guide canonical and crawlable layout')
check(all('id="'+x+'"' in t for x in ['audio-requirement','audio-compatibility','audio-design','audio-handover','audio-questions']),'Audio planning sections')
check('Recorded sound and' in t and 'two-way talk' in t and 'controlled recording' in t and 'separate device' in t,'Audio requirement and handover guidance')
check(t.count('class="accordion-item"')==10 and 'technical feature as automatic permission' in t and 'studio-quality audio' in t,'Useful audio questions and limits')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Audio guide Service schema')
check(get(audio+'.php')[1]==BASE+audio and get(audio+'/')[1]==BASE+audio,'Audio guide aliases redirect')
check('href="'+BASE+audio+'"' in get(home)[3],'Audio guide has contextual inbound link')
night='/cctv-night-vision-camera-installation-karachi'
s,u,h,t,p=get(night)
check(s==200 and p.canonical==BASE+night and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Night vision canonical and crawlable layout')
check(all('id="'+x+'"' in t for x in ['night-target','night-light','night-placement','night-testing','night-questions']),'Night vision planning sections')
check('recorded movement at the real distance' in t and 'Infrared and visible light' in t and 'play it back' in t,'Night target, lighting and recorded test guidance')
check(t.count('class="accordion-item"')==10 and 'advertised illumination distance is not an identification guarantee' in t and 'motion blur' in t,'Useful night vision questions and limits')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='Karachi' for x in p.schemas),'Night vision Service schema')
check(get(night+'.php')[1]==BASE+night and get(night+'/')[1]==BASE+night,'Night vision aliases redirect')
check('href="'+BASE+night+'"' in get(home)[3],'Night vision guide has contextual inbound link')
bahria='/cctv-camera-installation-bahria-town-karachi'
s,u,h,t,p=get(bahria)
check(s==200 and p.canonical==BASE+bahria and p.robots=='index, follow' and p.h1==1 and p.mains==1,'Bahria canonical, indexability and semantic layout')
check(t.count('<details class="dha-faq">')==10,'Bahria ten server-rendered answers')
check(all('id="'+x+'"' in t for x in ['bahria-coverage','bahria-design','bahria-process','bahria-faq']),'Bahria navigation targets exist')
check('precinct' in t and 'management permission' in t and 'Do not send passwords' in t and 'does not represent a Bahria Town branch office' in t,'Bahria practical access and honest local identity')
service=next(x for x in p.schemas if x.get('@type')=='Service')
check(service['areaServed']['name']=='Bahria Town Karachi' and service['url']==BASE+bahria,'Bahria Service schema matches page')
check('dha.css' in t and 'assets/optimized/service-home.webp' in t and '2026-10-09' in t,'Bahria styles, image and update date')
check(get(bahria+'.php')[1]==BASE+bahria and get(bahria+'/')[1]==BASE+bahria,'Bahria aliases redirect')
check(bahria in get('/')[3],'Homepage has crawlable Bahria link')
dha='/cctv-camera-installation-dha-karachi'
s,u,h,t,p=get(dha);check(s==200 and p.canonical==BASE+dha and p.robots=='index, follow' and p.h1==1,'DHA canonical, indexability and H1')
check('Phases 1–8' in t and all(('Phase '+str(i)) in t for i in range(1,9)),'DHA phases 1–8')
check('dha.css' in t and t.find('dha.css')<t.find('</head>') and 'assets/optimized/service-home.webp' in t,'DHA CSS in head and real compressed photo')
check(any(x.get('@type')=='Service' and x['areaServed']['name']=='DHA Karachi, Phases 1–8' for x in p.schemas),'DHA Service schema')
check(any(x.get('@type')=='FAQPage' for x in p.schemas) and 'wa.me/923091243189' in t and 'tel:+923091243189' in t,'DHA FAQs and direct CTAs')
check(get(dha+'.php')[1]==BASE+dha and get(dha+'/')[1]==BASE+dha,'DHA aliases redirect')
s,u,h,t,p=get('/sitemap.xml');root=ET.fromstring(t);ns={'s':'http://www.sitemaps.org/schemas/sitemap/0.9'};urls=[n.text for n in root.findall('s:url/s:loc',ns)]
check(BASE+home in urls and BASE+office in urls and BASE+shop in urls and BASE+maintenance in urls and BASE+ip in urls and BASE+access in urls and BASE+intercom in urls and BASE+imou in urls and BASE+storage in urls and BASE+power in urls and BASE+mobile in urls and BASE+cabling in urls and BASE+audio in urls and BASE+night in urls and BASE+dha in urls and BASE+bahria in urls and BASE+series in urls and not any('empty-category' in x or 'inactive-camera' in x for x in urls),'Sitemap canonical and active content only')
for url in urls:
    s,u,h,t,p=get(url[len(BASE):]);check(s==200 and p.canonical==url and 'noindex' not in p.robots,'Sitemap target valid: '+url)
print('SEO HTTP regressions passed, including all '+str(len(urls))+' fixture sitemap targets.')

